# Prepare Data

In [ ]:
import os

# All data lives under <repo-root>/datasets. ROOT_PATH climbs from this
# notebook's directory to the repo root (edit if you relocate the notebook).
ROOT_PATH = "../../.."
DATASETS = os.path.join(ROOT_PATH, "datasets")

In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv(f"{DATASETS}/corpus/eval.csv")

In [3]:
dataset.head()

                       text                                             pinyin
0            他赢了布什说我很高兴是他赢了  ta1 ying2 le bu4 shen2 shuo1 wo3 hen3 gao1 xin...
1            你根本想不到有多畅销赛义德说  ni3 gen1 ben3 xiang3 bu4 dao4 you3 duo1 chang4...
2    国家主席是个虚职实权掌握在共产党总书记的手里  guo2 jia1 zhu3 xi2 shi4 ge4 xu1 zhi2 shi2 quan...
3  如果你批评以色列政府有些人会因此说你是反犹主义者  ru2 guo3 ni3 pi1 ping2 yi3 se4 lie4 zheng4 fu3...
4            我是一十六号下次请还要叫我啊  wo3 shi4 yi1 shi2 liu4 hao4 xia4 ci4 qing3 hai...

# Bigram Count

## Raw

Raw bigram count (possibly with non-lexical units):

In [4]:
!pip install pypinyin

Requirement already satisfied: pypinyin in /home/user/miniconda/lib/python3.12/site-packages (0.55.0)

In [5]:
from collections import Counter
from tqdm import tqdm

bigram_freq = Counter()

for text in tqdm(dataset["text"]):

    text = str(text)

    for i in range(len(text) - 1):

        bigram = text[i:i+2]

        # skip punctuation etc.
        if len(bigram.strip()) != 2:
            continue

        bigram_freq[bigram] += 1

100%|██████████| 61704/61704 [00:02<00:00, 22051.32it/s]

In [6]:
import pandas as pd

bigram_df = pd.DataFrame(
    [
        (word, freq)
        for word, freq in bigram_freq.items()
    ],
    columns=["word", "freq"]
)

bigram_df = bigram_df.sort_values(
    "freq",
    ascending=False
)

bigram_df.head(20)

     word  freq
216    中国  6433
342    他们  5442
787    一个  5122
97     我们  4712
266    美国  3689
347    自己  3218
1781   可能  3002
2457   没有  2782
1081   的一  2685
70     一十  2572
2926   这个  2398
1061   这些  2331
53     政府  2325
3520   可以  2311
558    了一  2209
69     是一  2151
4819   的人  1971
429    二千  1957
1304   一些  1871
782    已经  1861

In [7]:
from pypinyin import lazy_pinyin, Style

def get_pinyin(word):
    return " ".join(
        lazy_pinyin(
            word,
            style=Style.TONE3
        )
    )

bigram_df["pinyin"] = bigram_df["word"].apply(
    get_pinyin
)

In [8]:
MIN_FREQ = 100

bigram_df = bigram_df[
    bigram_df["freq"] >= MIN_FREQ
].copy()

len(bigram_df)

2352

In [9]:
bigram_df.tail()

      word  freq       pinyin
14792   平等   100  ping2 deng3
7937    的真   100     de zhen1
4786    她是   100     ta1 shi4
1369    几周   100    ji3 zhou1
12437   克力   100      ke4 li4

## Word

Count of bigram lexical units (with `jieba`):

In [10]:
!pip install jieba

Requirement already satisfied: jieba in /usr/local/lib/python3.12/dist-packages (0.42.1)

In [10]:
import jieba
from collections import Counter
from tqdm import tqdm

word_freq = Counter()

for text in tqdm(dataset["text"]):

    words = jieba.lcut(str(text))

    for word in words:

        if len(word) < 2:
            continue

        word_freq[word] += 1

  0%|          | 0/61704 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.115 seconds.
Prefix dict has been built successfully.
100%|██████████| 61704/61704 [00:13<00:00, 4465.75it/s]

In [11]:
import pandas as pd

word_df = pd.DataFrame(
    [
        (word, freq)
        for word, freq in word_freq.items()
    ],
    columns=["word", "freq"]
)

word_df = word_df.sort_values(
    "freq",
    ascending=False
)

word_df.head(20)

     word  freq
71     中国  5893
116    他们  5442
281    一个  4835
28     我们  4711
89     美国  3382
118    自己  3167
848    没有  2732
611    可能  2714
1018   这个  2398
376    这些  2318
1221   可以  2308
149    二千  1868
279    已经  1861
453    一些  1861
1530   问题  1747
267   特朗普  1716
244    表示  1677
6      国家  1631
1138   这种  1593
305    政府  1582

In [13]:
word_df = word_df[
    word_df["word"].str.len() == 2
].copy()

len(word_df)

37890

In [14]:
word_df.head(20)

     word  freq
71     中国  5893
116    他们  5442
281    一个  4835
28     我们  4711
89     美国  3382
118    自己  3167
848    没有  2732
611    可能  2714
1018   这个  2398
376    这些  2318
1221   可以  2308
149    二千  1868
279    已经  1861
453    一些  1861
1530   问题  1747
244    表示  1677
6      国家  1631
1138   这种  1593
305    政府  1582
985    其他  1499

In [15]:
from pypinyin import lazy_pinyin, Style

def get_pinyin(word):

    return " ".join(
        lazy_pinyin(
            word,
            style=Style.TONE3
        )
    )

word_df["pinyin"] = word_df["word"].apply(
    get_pinyin
)

In [16]:
MIN_FREQ = 100

selected_word_df = word_df[
    word_df["freq"] >= MIN_FREQ
].copy()

len(selected_word_df)

1079

In [17]:
selected_word_df.tail()

     word  freq      pinyin
5707   举办   100    ju3 ban4
1463   兴趣   100   xing4 qu4
6042   经验   100  jing1 yan4
3007   遭遇   100    zao1 yu4
1415   多数   100   duo1 shu4

# Perturbation

## Prepare Homophones

In [18]:
import pickle as pkl

with open(f"{DATASETS}/probing/homophone_inventory.pkl", "rb") as f:
    homophone_inventory = pkl.load(f)

In [19]:
from collections import defaultdict

char_homophones = {}

for py, data in homophone_inventory.items():

    chars = data["chars"]
    freqs = data["freqs"]

    for i, char in enumerate(chars):

        alternatives = []

        for j, alt in enumerate(chars):

            if i == j:
                continue

            alternatives.append(
                (alt, freqs[j])
            )

        char_homophones[char] = alternatives

## Generation

In [20]:
import random
import numpy as np

random.seed(42)

def perturb_word(word):

    candidates = []

    for idx, char in enumerate(word):

        if char in char_homophones:

            candidates.append(
                (idx, char)
            )

    if not candidates:
        return None

    idx, original_char = random.choice(candidates)

    replacements = char_homophones[original_char]

    replacement_chars = [
        c for c, _ in replacements
    ]

    replacement_freqs = np.array(
        [f for _, f in replacements],
        dtype=float
    )

    replacement_probs = (
        replacement_freqs /
        replacement_freqs.sum()
    )

    replacement_char = np.random.choice(
        replacement_chars,
        p=replacement_probs
    )

    perturbed_word = (
        word[:idx]
        + replacement_char
        + word[idx+1:]
    )

    return {
        "position": idx,
        "original_char": original_char,
        "replacement_char": replacement_char,
        "original_word": word,
        "perturbed_word": perturbed_word
    }

In [21]:
MIN_PERTURBED_FREQ = 50

In [22]:
word_freq_lookup = dict(
    zip(word_df["word"], word_df["freq"])
)

In [23]:
from tqdm import tqdm

perturbations = []

for _, row in tqdm(selected_word_df.iterrows(),
                   total=len(selected_word_df)):

    word = row["word"]

    result = perturb_word(word)

    if result is None:
        continue

    perturbed_word = result["perturbed_word"]

    # Skip if perturbation is itself a frequent word
    # (e.g. 再见 -> 在见 should be discarded if 在见 is common enough)
    if word_freq_lookup.get(perturbed_word, 0) >= MIN_PERTURBED_FREQ:
        continue

    result["word_freq"] = row["freq"]
    result["perturbed_freq"] = word_freq_lookup.get(
        perturbed_word,
        0
    )

    perturbations.append(result)

perturbation_df = pd.DataFrame(perturbations)

100%|██████████| 1079/1079 [00:00<00:00, 4655.48it/s]

In [24]:
perturbation_df = pd.DataFrame(
    perturbations
)

perturbation_df.head()

,position,original_char,replacement_char,original_word,perturbed_word,word_freq,perturbed_freq
0,0,中,终,中国,终国,5893,0
1,1,个,各,一个,一各,4835,0
2,0,美,每,美国,每国,3382,0
3,0,自,字,自己,字己,3167,0
4,0,没,梅,没有,梅有,2732,0

In [25]:
perturbation_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   position          1021 non-null   int64
 1   original_char     1021 non-null   str
 2   replacement_char  1021 non-null   str
 3   original_word     1021 non-null   str
 4   perturbed_word    1021 non-null   str
 5   word_freq         1021 non-null   int64
 6   perturbed_freq    1021 non-null   int64
dtypes: int64(3), str(4)
memory usage: 73.9 KB

In [27]:
perturbation_df.to_csv(f"{DATASETS}/probing/exact_homophone_phrases.csv", index=False)